channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.6
  - snakemake>=5.10
  - pandas<1  # stay with old pandas
  - matplotlib>=3.1
  - seaborn>=0.9
  - jupyterlab>=2.2
  - altair>=4
  - scikit-bio>=0.5.5
  - scikit-learn>=0.21.3
  - ete3
  - r-base=4 # R dependencies
  - bioconductor-ggtree=2.2.1
  - bioconductor-microbiome=1.10.0
  - r-ape=5.4_1
  - r-broom=0.7.0
  - r-dplyr=1.0.2
  - r-ggplot2=3.3.2
  - r-pheatmap=1.0.12
  - r-phytools=0.7_47
  - r-plotly=4.9.2.1
  - r-purrr=0.3.4
  - r-readr=1.3.1
  - r-stringr=1.4.0
  - r-tibble=3.0.3
  - r-tidyr=1.1.2
  - r-vegan=2.5_6
  - r-kableextra=1.2.1
  - bioconductor-aldex2=1.20.0
