channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
 - bioconductor-ggtree=2.2.1
 - bioconductor-microbiome=1.10.0
 - r-ape=5.4_1
 - r-broom=0.7.0
 - r-dplyr=1.0.2
 - r-ggplot2=3.3.2
 - r-pheatmap=1.0.12
 - r-phytools=0.7_47
 - r-plotly=4.9.2.1
 - r-purrr=0.3.4
 - r-readr=1.3.1
 - r-stringr=1.4.0
 - r-tibble=3.0.3
 - r-tidyr=1.1.2
 - r-vegan=2.5_6
 - rstudio
