
name: 'Trigger-Binder-build'
on:
  push:
    branches:
      - master

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - name: cache binder build on mybinder.org
        uses: s-weigand/trigger-mybinder-build@v1.0.3
        with:
          target-repo: metagenome-atlas/Tutorial
          NO_PUSH: true
          MYBINDERORG_TAG: ${{ github.event.ref }}

