
name: 'Trigger-Binder-build'
on:
  push:
    branches:
      - tr_rmd

jobs:
  trigger-binder-build:
    runs-on: [ubuntu-latest]
    steps:
      - uses: s-weigand/trigger-mybinder-build@v1.0.3
        with:
          target-repo: metagenome-atlas/Tutorial
